#!/bin/bash

rm -fr htmlcov
coverage run --branch --source=config_onion -m pytest config_onion_test.py && coverage report -m && coverage html && \
    if [ "$1" == "open" ]; then xdg-open htmlcov/index.html; fi
